name: github pages

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/ricosjp/allgebra/doxygen:20.10.1
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 0.14.0
    - name: Generate document
      run: |
        doxygen
        mv html public/0.14.0
    - uses: actions/upload-artifact@v2
      with:
        name: doxygen-0.14.0
        path: public/0.14.0

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: doxygen-0.14.0
        path: public/0.14.0
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/
        force_orphan: true
