name: github pages

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ricosjp/allgebra/doxygen:20.10.1
    strategy:
      matrix:
        version:
          - 0.14.0
          - 0.14.1
          - 0.14.2
          - master
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.version }}
    - name: Generate document
      run: |
        doxygen
        mkdir -p public
        mv html public/${{ matrix.version }}
    - uses: actions/upload-artifact@v2
      with:
        name: doxygen-${{ matrix.version }}
        path: public/${{ matrix.version }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: actions/download-artifact@v2
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/
        force_orphan: true
